iscsiuio/src/unix/nic_nl.c
Hello all,
this pull request adresses segfaults from iscsiuio. The issue has particularly been
seen on newer Intel CPUs (Broadwell, probably Skylake too). For a more detailed
discussion, please refer to:
https://groups.google.com/forum/#!topic/open-iscsi/990rkk-90_A
Thanks & best regards,
Frank Fegert
=> Segfaults from iscsiuio (iscsiuio/src/unix/nic_nl.c)

README
Nothing more, nothing less. (c;
=> Fix a bunch of typos and a bit of wording.

README
=> Improve README punctuation.

README
It seems there's still conflicts… :innocent:
=> Uniform invocation examples

iscsiuio/README, iscsiuio/RELEASE.TXT, iscsiuio/configure.ac, iscsiuio/src/unix/libs/cnic.c
Please consider the iscsiuio bug fix for upstream.
Thanks,
Nilesh
=> Iscsiuio bug fixes

usr/iscsistart.c
iscsi boot performance can be improved by sleep() with finer
grained interval and exponential backoff.
Signed-off-by: Cathy Zhou <Cathy.Zhou@Oracle.COM>
=> Reduce delays to improve iscsi boot performance

etc/systemd/iscsi.service, etc/systemd/iscsid.service, etc/systemd/iscsid.socket, usr/event_poll.c, usr/event_poll.h, usr/iscsi_sysfs.c, usr/iscsi_sysfs.h, usr/iscsid.c
NOTE: This REQUIRES an update to the sytemd unit service file iscsid.service. See commit comments.
=> Use sd notify for systemd

usr/iscsiadm.c
The output of "iscsiadmm -m node -P*" changed when
libopeniscsiusr was merged, and an earlier attempt was
made to clean it up (see commit 59806c99fb3f). This
commit fixes output so that. Before this fix, if one
had multiple paths to the same target, the output
of "iscsiadm -m node -P1" would be:
> Target: iqn.2008-04.net.gonzoleeman:01:disk1
>         Portal: 10.0.0.1:3260,1
>                 Iface Name: default
> Target: iqn.2008-04.net.gonzoleeman:01:disk1
>         Portal: 10.0.1.1:3260,2
>                 Iface Name: default
But this commit fixes the output to be that of iscsiadm
before the libopeniscsiusr merge, i.e.:
> Target: iqn.2008-04.net.gonzoleeman:01:disk1
>         Portal: 10.0.0.1:3260,1
>                 Iface Name: default
>         Portal: 10.0.1.1:3260,2
> …
=> Fix output of node printing for multiple paths.

iscsiuio/README, iscsiuio/RELEASE.TXT, iscsiuio/configure.ac, iscsiuio/src/unix/nic.c
Please consider iscsiuio bug fix in the MPIO config.
Thanks,
Nilesh
=> iscsiuio bug fix

.travis.yml, doc/iscsi-iname.8, iscsiuio/src/uip/ipv6.c, iscsiuio/src/unix/libs/qedi.c, iscsiuio/src/unix/main.c, iscsiuio/src/unix/nic_nl.c, iscsiuio/src/unix/nic_utils.c, usr/auth.c, usr/host.c, usr/iscsi_net_util.c, usr/iscsi_sysfs.c, usr/iscsi_util.c, usr/iscsiadm.c, usr/iscsid_req.c, usr/sysfs.c, utils/fwparam_ibft/fwparam_ppc.c, utils/iscsi-iname.c
This closes out 31 reported "high impact" issues.
=> first batch of changes to address Coverity scan issues

etc/iscsid.conf
Signed-off-by: Rafael David Tinoco <rafaeldtinoco@ubuntu.com>
=> Misspelled socket name might cause confusion to inexperienced user.

usr/iscsiadm.c
The mode parameters should be check earlier when recognize the
mode, rather than mutiple calls after all commandline parameters
are parsed.
Signed-off-by: Wu Bo <wubo40@huawei.com>
Signed-off-by: Zhiqiang Liu <liuzhiqiang26@huawei.com>
=> iscsiadm: Optimize the the verification of mode paramters

.gitignore, iscsiuio/src/unix/iscsid_ipc.c, iscsiuio/src/unix/libs/bnx2x.c, iscsiuio/src/unix/libs/qedi.c, usr/idbm.c, usr/idbm.h, usr/iscsi_net_util.c, usr/iscsi_sysfs.c, usr/iscsiadm.c, usr/iscsistart.c, usr/mgmt_ipc.c, usr/sysfs.c, utils/fwparam_ibft/fwparam_ppc.c, utils/iscsi-iname.c
Recently, we use Coverity to analysis the open-iscsi package.
Several issues should be resolved to make Coverity happy.
=> fix serverl issues reported by Coverity

libopeniscsiusr/context.c, libopeniscsiusr/node.c, libopeniscsiusr/session.c, usr/idbm.c, usr/iscsiadm.c
I reviewed the open-iscsi code and found some memory leaks, this PR is to fix these bugs
=> Fix 4 memory leak in source code

test/harness/util.py
Fix s/sttderr/stderr typo in line 179 of util.py
=> Fix typo in util.py

doc/iscsiadm.8, usr/iscsiadm.c
In addition, update the iscsiadm help message, and the
iscsiadm man page.
=> Add iscsiadm "no wait" option for firmware login.

usr/iscsi_sysfs.c
In 5.6, the commit:
commit 0ab710458da113a71c461c4df27e7f1353d9f864
Author: Bharath Ravi <rbharath@google.com>
Date:   Sat Jan 25 01:19:25 2020 -0500
scsi: iscsi: Perform connection failure entirely in kernel space
made it so the kernel can start the recovery process. This means that
after the start conn operation the kernel could set the device into the
block stated. We can then hit a race where iscsid has done start conn,
and is calling session_online_devs but the kernel has hit an issue and is
now setting the device's to blocked.
This adds a check for if the device is in the offline state before trying
to set the state to running.
=> iscsi sysfs: check state before onlining devs

usr/idbm.c
PR for #306.
Feel free to make edits if necessary, thanks!
=> Fix minor error string typos

doc/iscsiadm.8
Removed duplicate spaces, fixed spellings, reworded some
stuff to be more clear, and tried to be consistent about
showing keywords in itallics/emphasis.
=> Cleanup iscsiadm man page

Makefile, doc/Makefile, iscsiuio/Makefile.am
Fixes DESTDIR issue with install
=> Fix destdir install for iname

iscsiuio/src/unix/nic_utils.c
Fix a missing-unlocking bug in nic_utils.c
=> Fix a missing-unlocking bug

doc/iscsiadm.8.template
Added examples in man file for iscsiadm session commands.
Signed-off-by: Max Cheng <mchngc@gmail.com>
=> Added examples in man file for iscsiadm session commands.

usr/iface.c
PR for https://github.com/open-iscsi/open-iscsi/issues/355
Please feel free to make edits. Thanks!
=> Fix a possible passing null pointer in usr/iface.c

.gitignore, Makefile, README, doc/meson.build, etc/meson.build, etc/systemd/meson.build, iscsiuio/README, iscsiuio/docs/meson.build, iscsiuio/meson.build, iscsiuio/src/apps/brcm-iscsi/meson.build, iscsiuio/src/apps/dhcpc/meson.build, iscsiuio/src/apps/meson.build, iscsiuio/src/meson.build, iscsiuio/src/uip/meson.build, iscsiuio/src/unix/build_date.sh, iscsiuio/src/unix/libs/meson.build, iscsiuio/src/unix/meson.build, libopeniscsiusr/docs/meson.build, libopeniscsiusr/libopeniscsiusr/meson.build, libopeniscsiusr/meson.build, libopeniscsiusr/tests/meson.build, meson.build, meson_options.txt, sysdeps/meson.build, usr/fwparam_ibft/meson.build, usr/meson.build, utils/iscsi-iname.c, utils/meson.build
Set up to be able to build using meson/ninja, but leave the current make/autoconf system in place.
=> Use meson as the main build system

iscsiuio/src/uip/lc-switch.h
=> Fix a typo error in iscsiuio/src/uip/lc-switch.h

meson_options.txt, usr/discovery.c
Some cleanup of discovery.c, and of the meson build options. No functional changes.
=> Small cleanup

include/iscsi_if.h
Adds definition for ISCSI_UEVENT_DESTROY_SESSION_ASYNC
Replaces zero-length array with C99 flexible array member
=> sync iscsi_if.h with kernel

README
=> README: add info about disabling NOPs for tape.

meson.build, usr/iface.c
Does anyone not build with this enabled?
=> remove OFFLOAD_BOOT_SUPPORTED ifdef

usr/auth.c
algorthm -> algorithm
Spotted in syslog (under FIPS mode).
=> Spelling fixes

iscsiuio/src/apps/dhcpc/dhcpc.c, iscsiuio/src/apps/dhcpc/dhcpv6.c, iscsiuio/src/uip/ipv6.c, iscsiuio/src/uip/ipv6_ndpc.c, iscsiuio/src/uip/uip-neighbor.c, iscsiuio/src/uip/uip.c, iscsiuio/src/uip/uip_arp.c, iscsiuio/src/unix/iscsid_ipc.c, iscsiuio/src/unix/libs/bnx2.c, iscsiuio/src/unix/libs/bnx2x.c, iscsiuio/src/unix/libs/cnic.c, iscsiuio/src/unix/libs/qedi.c, iscsiuio/src/unix/logger.c, iscsiuio/src/unix/logger.h, iscsiuio/src/unix/main.c, iscsiuio/src/unix/nic.c, iscsiuio/src/unix/nic.h, iscsiuio/src/unix/nic_id.c, iscsiuio/src/unix/nic_nl.c, iscsiuio/src/unix/nic_utils.c, iscsiuio/src/unix/nic_utils.h, iscsiuio/src/unix/nic_vlan.c, iscsiuio/src/unix/packet.c, iscsiuio/src/unix/ping.c
Multiple changes to iscsiuio to fix some instability, particularly when shutting down. This does not fix everything, but it's pretty close, I believe.
=> Iscsiuio fixes v2

README
Hi,
just found some missing chars in the README.
=> Adds missing characters in README.

libopeniscsiusr/idbm.c, usr/idbm.c
=> improve the comments in idbm_lock()

usr/iscsi_util.c, usr/iscsi_util.h, usr/iscsiadm.c
Fix two small issues found by gcc7 in iscsiadm/iscsid. No functional chanages.
=> Fix gcc issues

usr/discovery.c
Just converting a function that returned an ignored value to a void function. No functional change.
=> Fix one funct

usr/discovery.c, usr/discoveryd.c, usr/host.c, usr/idbm.c, usr/iface.h, usr/initiator.c, usr/initiator.h, usr/initiator_common.c, usr/io.c, usr/iscsi_sysfs.c, usr/iscsid.c, usr/iscsistart.c, usr/mntcheck.c, usr/session_mgmt.c
Hi!When I build with clang 17,I got 4 errors with -Werror.
This pr fix issue #473 #474 #475 #476  .
You can take my modifying methods or use better methods,hopelly the bugs will be fixed.
Thanks!
=> fix 4 issues which are finded when building with clang 17

test/README
```
-  * bonie++
+  * bonnie++
```
=> Fix a typo in test/README

usr/io.c
When an interface goes down and later comes back up, there is a window where the link is up but no IP address has been assigned yet. In this state, an immediate reconnect attempt can lead to unexpected behavior.
Consider this scenario:
On the initiator side with two interfaces (re0 and re1) connected to the target via a switch, consider the following sequence:
- re1 goes down and its IP address is moved to re0 as part of failover.
- re0 communicates with the target, which then caches re0's IP along with its hardware address in arp table.
- Later, re1 comes back online. When the link first comes up, there is a short window where no IP is assigned to re1.
- If iSCSI attempts to reconnect during this window, it will (by design) fall back to using another interface with a valid IP. In this …
=> iscsi: delay reconnect until interface has valid IP.
