open-iscsi/open-iscsi

- README
The path to the kernel include files is given by
/lib/modules/`uname -r`/build
on Debian.
Signed-off-by: Heinrich Schuchardt <xypron.glpk@gmx.de>
> Kernel include path

- doc/iscsiadm.8
Also remove trailing whitespaces.
Signed-off-by: Christophe Vu-Brugier <cvubrugier@fastmail.fm>
> Fix typos in iscsiadm man page

- utils/fwparam_ibft/fwparam_ibft_sysfs.c
A recent change, commit 4959a89f421fdebc, modified open-iscsi
to treat the "origin" field as an enum, not a character
string. But one spot was missed.
> iBFT 'origin' is an enum, not a string

- etc/iscsid.conf
- usr/config.h
- usr/idbm.c
- usr/idbm.h
- usr/idbm_fields.h
- usr/initiator.c
- usr/iscsi_settings.h
- usr/iscsi_sysfs.c
- usr/iscsi_sysfs.h
- usr/iscsiadm.c
- usr/iscsid.c
- usr/iscsistart.c
Allow disabling auto LUN scans
Existing behavior of auto scanning LUNs is problematic for some
deployments, particularly in cases where we are:
- Accessing different LUNs from the same target on different machines
and we don't want the other LUNs automatically exposed in other
systems.
- LUNs are constantly being created and removed from the target by
another machine and we don't want our systems polluted by no longer
available logical units, since default udev rules don't remove them
automatically from the system once they have been added automatically.
This is a little more problematic when working with multipaths as we end
up with a lot of leftover device maps.
This patch introduces a new configuration option at the session level
called "scan", with "auto" and "manual" as acceptable …
> Allow disabling auto LUN scans

- README
This commit…
- promotes section 1.1 "Features" to a full-fledged heading,
- removes unnecessary indentation in section 1.1,
- adds a uniform amount of newlines before (2 lines) and after each heading+"underline" (1 line),
- replaces all heading "underlines" with equals signs (some where minuses before),
- removes some trailing colons and whitespace from headings.
> Unify README headings.

- README
- Remove some trailing whitespace;
- Unify-replace some spaces with tabs;
- Add some empty lines for readability and uniformity.
> Cleanup README whitespace.

- usr/iscsi_sysfs.c
- usr/iscsi_sysfs.h
The newly introduced feature to disable automatic scans should not be
scanning *any* of the LUNs when the scan is set to manual, but it always
scans for LUN0.
This patch fixes this by skipping the sysfs call altogether, as it
should have been doing from the start.
> Fix manual LUN scans feature

- usr/session_info.c
A recent commit 2b099d7b7e04b "Use timeout when waiting for responses from iscsid" introduced a bug in session_info_print() when running "iscsiadm -m session -P <LEVEL>", where LEVEL was 1 or 2. The bug was that "info" was being dereferenced to get a timeout value when "info" was NULL. This fix just uses the default timeout in that case and testing has shown it fixes the issue.
> Fix coredump when printing sessio info at level 1 or higher

- usr/transport.c
iscsiuio ping is operational for qedi.
Add missing qedi transport hook for ping support.
Signed-off-by: Nilesh Javali <nilesh.javali@cavium.com>
> iscsid: Add qedi ping transport hook

- iscsiuio/src/apps/dhcpc/dhcpv6.c
- iscsiuio/src/unix/libs/bnx2x.c
- iscsiuio/src/unix/libs/cnic.c
- iscsiuio/src/unix/libs/qedi.c
Initialize the transaction-id within the dhcpv6 packet with
correct byte order.
Signed-off-by: Nilesh Javali <nilesh.javali@cavium.com>
> iscsiuio bug fixes

- usr/iscsiadm.c
This fixes an issue where the SSL library initialization can return an error on non-MIPS-enabled systems, which can leave the C-library "errno" dirty, i.e. having a non-zero value. This just initializes errno to zero before the two places where we later check it for an error being returned.
> Strtoull fix

- iscsiuio/src/unix/libs/bnx2.c
- iscsiuio/src/unix/libs/bnx2x.c
Release notes for glibc-2.25 state:
The inclusion of <sys/sysmacros.h> by <sys/types.h> is deprecated.
This means that in a future release, the macros “major”, “minor”, and
“makedev” will only be available from <sys/sysmacros.h>.
These macros are not part of POSIX nor XSI, and their names frequently
collide with user code; see for instance glibc bug 19239 and Red Hat
bug 130601. <stdlib.h> includes <sys/types.h> under _GNU_SOURCE, and
C++ code presently cannot avoid being compiled under _GNU_SOURCE,
exacerbating the problem.
This results in the following errors:
bnx2.c: In function ‘bnx2_open’:
bnx2.c:482:19: warning: implicit declaration of function ‘minor’; did you mean ‘mknod’? [-Wimplicit-function-declaration]
nic->uio_minor = minor(uio_stat.st_rdev);
bnx2x.c: In function …
> Inclusion of <sys/sysmacros.h> by <sys/types.h> is deprecated.

- include/iscsi_net_util.h
- iscsiuio/docs/iscsiuio.8
- iscsiuio/src/unix/main.c
- usr/iscsi_net_util.c
- utils/fwparam_ibft/fw_entry.c
Add support in iscsistart for bnx2{,x} software initiators. This allows boot from iSCSI for devices that either cannot support iSCSI hardware offload or are configured in firmware not to support it.
The scsistart -N option will now bring up the interface (but not configure it) as specified in the IBFT for hardware offload devices.
Note: I cannot find a way to programmatically determine whether a bnx2{,x} device is configured for
hardware or software, so we check for the presence of the iscsiuio executable as an indication that hardware offload is being used.
> Add bnx2{,x} software initiator IBFT support

- .gitignore
After years of see these build files listed when I do "git status", I'm ready to add them to the ignore list.
> Ignore common build output files

- Makefile
- doc/iscsi_fw_login.8
- utils/50-iscsi-firmware-login.rules
- utils/iscsi_fw_login
Add a script that logs into all iSCSI firmware
targets, and add a udev rule to call that script
when new targets are detected. Also, add a
man page for the script.
> Automate logging into iSCSI FW targets.

- etc/iscsid.conf
The comments for this attribute were outdated. In
general, with systemd, we do not want to manually
start the iscsid daemon ourselves.
> Update iscsid.conf attribute iscsid.startup.

- iscsiuio/Makefile.am
Make sure needed directories exist, and make
sure install/symbolic linking of target
works, even when not in root=/.
> Cleanup iscsiuio master Makefile template.

- Makefile
This is just cleanup, as these scripts and man pages
are present but just not named in the top-level Makefile.
> Add some scripts and manpages to the top Makefile.

- include/fw_context.h
- usr/config.h
- usr/idbm.c
- usr/idbm_fields.h
- utils/fwparam_ibft/fw_entry.c
- utils/fwparam_ibft/fwparam_sysfs.c
The modern IP standard stresses the IP prefix length
rather than the network mask, so track the IP prefix length
from sysfs and in the interface DB.
> Add in tracking IP prefix length, in addition to mask.

- usr/discoveryd.c
The "ipc" variable was being set to NULL because
the discovery code was thought to rely on that
value, but that was not the case, and non-tcp
transport needs this variable set to its
default (non-null) value to work.
> Discovery via non-tcp transport needs "ipc" value

- usr/iscsid.c
Changing log level for daemon start message.
This is not an error, just an info.
> iscsid: fix logging level when starting daemon

- TODO
- include/iscsi_if.h
For some reason not clear to me open-iscsi has it's own copy of iscsi_if.h which should match the kernel version, so that when iscsid talks to the kernel, they speak the same enums. So add some new enums to our version of the file, and add a comment about keeping the files in sync.
This change also adds a TODO item to try to remedy this duplication.
> Update iscsi if to latest

- libopeniscsiusr/iface.c
In libopeniscsiusr, when getting iface from
sysfs, allow a host_id of zero, since the
host_id starts at zero. The fact that it
is a uint32_t is enough of a limitation.
> Allow a host_id value of zero.

- utils/fwparam_ibft/fw_entry.c
The qedi offload iface does not have netdev associated with it.
Correctly get the transport_name from boot context.
iBFT and offload iface can rely on this method to get the
transport name.
Signed-off-by: Nilesh Javali <nilesh.javali@cavium.com>
> iscsiadm: get transport_name correctly for offload iface

- libopeniscsiusr/idbm.c
- libopeniscsiusr/idbm_fields.h
- libopeniscsiusr/iface.c
- libopeniscsiusr/iface.h
- libopeniscsiusr/misc.h
- libopeniscsiusr/node.c
- libopeniscsiusr/session.c
- libopeniscsiusr/sysfs.c
- libopeniscsiusr/sysfs.h
Fixes for iface handling regressions after merging the libopeniscsiusr code.
Found while testing under a variety of iSCSI HBAs (be2iscsi, qla4xxx, bnx2i, qedi)
> Libopeniscsiusr fixes

- iscsiuio/src/unix/libs/cnic.c
- iscsiuio/src/unix/libs/qedi.c
- iscsiuio/src/unix/nic.c
- iscsiuio/src/unix/nic_utils.c
- usr/iscsi_sysfs.c
This avoids the netlink buffer corruption when more than one host
try to xmit packet at the same time.
Signed-off-by: Manish Rangankar <manish.rangankar@cavium.com>
> iscsiuio: Add inter-host mutex while doing xmit

- usr/initiator.h
- usr/initiator_common.c
- usr/login.c
The iscsi_tcp kernel side R2T handling is in libiscsi_tcp and is shared
with at least cxgbi3, and the drivers claim CAP_MULTI_R2T. But the
iscsid login parameter negotiation code never enabled MaxOutstandingR2T.
I've tested this against an LIO target, negotiating to 2 and 4 R2Ts.
The network traces looked good, with the initiator keeping track of
multiple outstanding R2Ts and using the correct next identifier.
Throughput of bulk write data was improved, even over low latency virtio
links.
Signed-off-by: Chris Leech <cleech@redhat.com>
> enable MaxOutstandingR2T negotiation

- usr/discovery.c
During discovery the function get_op_params_text_keys()
can allocate a target_alias, but this is never freed.
Discovered-by: zhangzujian.7@gmail.com
> Plugging a memory leak from discovery.

- iscsiuio/src/unix/main.c
- iscsiuio/src/unix/nic_nl.c
As discussed in issue #125 there are a few non critical cleanups that could be done.
Due to the way nic_nl_open is currently called from main these changes should not change execution but will help to avoid breaking things later by accident - for example by inserting code in main after the nic_nl_open call.
Fixes #125
> Cleanup nic nl open usage

- etc/iscsid.conf
- include/iscsi_err.h
- libopeniscsiusr/default.c
- libopeniscsiusr/default.h
- libopeniscsiusr/idbm.c
- libopeniscsiusr/idbm_fields.h
- libopeniscsiusr/session.c
- libopeniscsiusr/sysfs.c
- usr/idbm.c
- usr/idbm_fields.h
- usr/initiator.c
- usr/initiator.h
- usr/iscsi_err.c
- usr/iscsi_settings.h
This set of changes includes some bug fixes for existing problems, but they were problems related to the main issue, so they are fixed as well.
The main issue is that iscsid tries to reconnect "stale" sessions it finds when it starts up, and it does this forever. So we limit that, and we fix up access to the session during that time, as well.
> Limit iscsid infinite session reconnect attempts at startup using a new config value

- usr/initiator_common.c
- usr/iscsid_req.c
- utils/fwparam_ibft/fwparam_ppc.c
I was tired of seeing 3 non-fatal warnings when compiling so this fixes them. Gcc8 is now much happier.
> Small cleanups

- usr/session_mgmt.c
If a request is made to login to a target, creating
a session, then another request is submitted so quickly
that the first one has not completed, both  requests
can succeed, despite having nr_sessions=1 configured.
Only allow multiple login requests if nr_sessions is
greater than 1.
> Do not allow multiple sessions when nr_sessions=1

- etc/iscsid.conf
- usr/initiator.c
Commit b9afe4709900 added a configuration variable for session
reconnect called reopen_max that defaults to 32. This changes the
behavior of iscsid on startup if it finds any session information
left over from previous invocations. Adding the option of setting
the retry count to zero to imply previous behavior allows those
that are counting on this behavior to continue. But, make no
mistake, it is recommended not to retry forever, as it leaves
iscsid stuck in "iscsi_sysfs_for_each_session()" in iscsid.c:main(),
so iscsid never fully gets up and running.
> When reopen_max=0 retry reopening forever.

- libopeniscsiusr/iface.c
- usr/transport.c
There is no reason to continue to use fork/exec to probe
for modules, so remove the code that supported this.
See issue #113
> Use libkmod instead of fork/exec of modprobe.

- etc/iscsid.conf
- libopeniscsiusr/default.h
- usr/iscsi_settings.h
The daemon has traditionally tried to recover stale
sessions, at startup, in serial and in a forked process.
A recent commit, b9afe4709900, added the ability to limit
these retries, and it made the default 32. Commit
467946a945cc added back in the ability to retry forever,
if the retry count was set to 0, but left the default
at 32. This commit changes the default to 0, so as
not to disrupt the expected reconnection behavior by
default.
> Make reconnect to session on startup forever default.

- usr/iscsiadm.c
As part of the libopeniscsiusr update, the output
of "iscsiadm -m node" dropped a space that needs to
be between the portal and the target, for proper
parsing.
Fixes: 87ea50a1c3a97
> Restore space in node-mode level 0 output

- iscsiuio/src/unix/nic.c
Unlike bnx2x, qedi start_xmit netlink provide us guarantee
of transmitting LL2 packet, so there is no need to call clear_tx_intr for
each LL2 packet. This help us in reducing iscsiuio lock contention.
Signed-off-by: Manish Rangankar <manish.rangankar@cavium.com>
> iscsiuio: Do not flush tx queue on each uio interrupt.

- libopeniscsiusr/idbm.c
- usr/idbm.c
Gcc7 warns of possible string print overflow, on i586,
when printing password length (via a macro), generating
errors like:
[   59s]   ^~~~~~~~~~~~~~~~~~~~
[   59s] In file included from /usr/include/stdio.h:862:0,
[   59s]                  from idbm.h:27,
[   59s]                  from context.h:22,
[   59s]                  from idbm.c:59:
[   59s] /usr/include/bits/stdio2.h:64:10: note:
'__builtin___snprintf_chk' output between 2 and 11 bytes into a
destination of size 8
[   59s]    return __builtin___snprintf_chk (__s, __n,
__USE_FORTIFY_LEVEL - 1,
[   59s]           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~
[   59s]         __bos (__s), __fmt, __va_arg_pack ());
[   59s]         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   59s] cc1: all warnings being treated as …
> Fix i586 build issues with string length overflow.

- libopeniscsiusr/Makefile
- usr/Makefile
These two recently-added libraries can be in different
locations on different distros, so use pkg-config to
added the appropriate actions in the make files.
> Use pkg-config in Makefiles for newer libraries.

- etc/systemd/iscsi.service
This will ensure daemon is loaded before iscsi.service starts. Also in case daemon fails to load iscsi.service will not be started.
> Make iscsid.service a requirement.

- etc/systemd/iscsi.service
Now only code 21 (no objects found to execute on) and normal exit conditions are valid.
> Fixed iscsi.service considering every signal and exit code as successful

- usr/iscsiadm.c
When we switched to using libopeniscsiusr, the behavior of iscsiadm
when running "iscsiadm -m node" diverged with that seen when
running "iscsiadm -m node --op show", whereas before that time
(version 2.0.873) was the same for these two cases. Note that
iscsiadm return value used to be the same in both cases, i.e.
returning 21, meaning "no targets found", but now returns
21 for the "--op show" case and zero for the other.
The fix is simple: rip out the code in iscsiadm that treats
"iscsiadm -m node" as a special case, allowing the code to fall
through to its previous behavior.
> Fix node print return value when no nodes.

- etc/systemd/iscsid.service
This change adds Restart=on-failure systemd service option to iscsid.service config file so that iscsid daemon is restarted on failure.  This option is particularly useful when using iscsi boot device and iscsid daemon crashes or is inadvertently killed.
> Add Restart=on-failure option to iscsid.service

- usr/iscsiadm.c
This fixes commit ec2afb8a1c997bac706de4f70a3a59fdd82b5741,
which aimed to make the return value from "iscsiadm -m node -P[01]"
return the correct value of "21", for no targets found. But
instead it make the output of all "iscsiadm -m node -P*" act like
the output of "iscsiadm -m node --op show", which was just wrong.
Instead, revert the above-mentioned commit, then add a simple
check for "no nodes" in print_nodes().
> Fix printing of node database again.

- usr/discovery.c
If session reopening failed during discovery, the CPU
could peg at 100% because the code that gives up when
tretires are exhausted was not setting an error
return value.
> Fix possible discovery hang when timing out

- doc/iscsid.8
- etc/initd/initd.debian
- etc/initd/initd.redhat
- etc/systemd/iscsiuio.service
- etc/systemd/iscsiuio.socket
- iscsiuio/docs/iscsiuio.8
- iscsiuio/src/unix/logger.c
- iscsiuio/src/unix/main.c
- libopeniscsiusr/idbm.c
- usr/initiator.h
This group of commits brings iscsiuio up to date with iscsid, in that it adds support for systemd at startup time, but in this case it can be ifdefed out, for those cases when systemd is not available.
It also adds example systemd service and socket files for iscsiuio, and it cleans up the error messages in iscsiuio, which didn't all have newlines, and were being dumped to stdout.
Lastly, for those still wishing to use daemon (non-foreground) mode for iscsiuio, I add a handshake between parent and child when becoming a daemon, so that the parent does not exit until the child is actually ready to do business.
> Fix systemd startup etc

- Makefile
- usr/Makefile
- usr/iscsid.c
You can compile without system now by using something
like:
make OPTFLAGS="-DNO_SYSTEMD ..." NO_SYSTEMD=1
This will skip systemd code for iscsid and iscsiuio.
> Make iscsid systemd usage optional

- usr/idbm.c
- usr/idbm.h
- usr/iface.c
- usr/iscsiadm.c
- usr/iscsid.c
The iscsiadm is getting a file lock while writing out records, and
updates are a read-modify-write operation and currently only the
write is locked.
So the parallel requests are reading in the pre-update record and
then overwriting each other with the writes.
Fixing RHBZ#1624670
Signed-off-by: Xiubo Li <xiubli@redhat.com>
> rec update: disable the idbm_lock in read/write when updating the rec

- etc/systemd/iscsi.service
The iscsi.service systemd unit file, which controls
iscsi logins and logouts, should be stopped if the
iscsid service file is stopped.
> The iscsi login/logout service requires iscsid.

- Makefile
The added target `install_systemd` can install the systemd units.
> Add make target to install systemd units

- usr/iscsiadm.c
When printing session info from iscsiadm, the following worked:
> # iscsiadm -m session -r N      -- print session info for session N
> # iscsiadm -m session -s        -- print session stats for all sessions
But this did not:
> # iscsiadm -m session -r N -s   -- print session stats for session N
Which is the same as the simple "-s" form if there is just one session.
To fix this error, initialize the timeout to "none" (-1) when sending
our request to iscsi for session stats, as do other requests.
> Initialize timeout for printing specific session info.

- .travis.yml
Configure Travis-CI for automated build tests.
Hopefully we can extend this to basic functional as well.
Also sets up Coverity scanning from the Travis build.
Synopsys gives Open Source projects a limited number of free Coverity
scans each day, so this is currently configured to only scan when code
is pushed to a "coverity_scan" branch.
> setup Travis-CI builds and Coverity scans

- etc/iscsid.conf
- libopeniscsiusr/default.c
- libopeniscsiusr/idbm.c
- libopeniscsiusr/idbm.h
- libopeniscsiusr/idbm_fields.h
- usr/auth.c
- usr/auth.h
- usr/config.h
- usr/idbm.c
- usr/idbm.h
- usr/idbm_fields.h
- usr/initiator.h
- usr/initiator_common.c
- usr/login.c
Introduces support for preference lists in configuration files, and uses
that for the 'node.session.auth.chap_algs' setting.
This is also re-used for discovery authentication, rather than have two
different configurations.
It turns out that adding to the configuration file is way harder than adding new digest algorithms to the CHAP code itself was.  Having two sets of idbm.c to worry about depending on which commands are being run really doesn't help either.
I've tried breaking this every way I can think of, and I can't make it fall over anymore.
It seems far enough along to share.  Let me know if you spot anything that needs changing.
> configuration support for CHAP algorithms

- libopeniscsiusr/libopeniscsiusr.pc.in
The library name is libopeniscsiusr, so the -l linker option should be `-lopeniscsiusr` instead of `-liscsiusr`.
> Fix bug with libopeniscsiusr.pc

- usr/iscsiadm.c
OS is stuck after reboot command on iscsi boot environment. 
The root cause is that the systemd can't access the iscsi boot disk after iscsi service was stopped by
reboot command. So the systemd can't execute remaining jobs. As a result, OS is stuck.
This patch avoids logout of iscsi boot session.
> Avoid logout of iscsi boot session

- libopeniscsiusr/idbm.c
Running "make check" in the libopeniscsiusr directory found
two memory leaks. The fix was to free the memory.
> Fix memory leaks in libopeniscsiusr/idbm.c

- usr/iscsi_net_util.c
In find_vlan_dev func, socket should be checked before used.
Signed-off-by: Zhiqiang Liu <liuzhiqiang26@huawei.com>
> Check whether socket is opened successfully in find_vlan_dev func

- Changelog
- libopeniscsiusr/version.h
- usr/version.h
I will tag a new version if there are no objections. This has several useful bug fixes since 2.1.0.
> Preparing for version 2.1.1

- etc/systemd/iscsi.service
Requiring iscsid.service means that a restart of iscsi.service
restarted iscsid.service when unneccesary.
Also, we should treat an exit value of 15 as normal, since
this just means the session is already present.
It should rely on iscsid.socket, no iscsid.service.
> Fix iscsi.service so it handles restarts better

- utils/Makefile
- utils/iscsi-iname.c
While I was at it, I made the usage message a function
and made it print to stderr insted of stdout.
> Fix issue where "iscsi-iname -p" core dumps.

- etc/systemd/iscsid.service
- etc/systemd/iscsiuio.service
This ensures that either iscsiuio or iscsid service
makes sure the remote-fs-pre is run after.
> Add Wants=remote-fs-pre.target for sequencing.

- iscsiuio/src/unix/nic_nl.c
- usr/discovery.c
- usr/event_poll.c
- usr/io.c
- usr/iscsi_util.c
- usr/iscsistart.c
- usr/mgmt_ipc.c
- usr/netlink.c
- usr/statics.c
Some changes to support the "musl" minimalist C library. There should be no functional changes.
> Fix musl compiles v2

- usr/iface.c
Just a cleanup, as looking at the example file
didn't hurt anything, but did waste our time.
> Ignore iface.example in iface match checks

- utils/iscsi-iname.c
Iscsid log damon is responsible for reading data from shared memory
and writing syslog. Iscsid is the root user group.
Currently, it is not seen that non-root users need to read logs.
The principle of minimizing the use of permissions, all the permissions are changed from 644 to 600.
Signed-off-by: Wu Bo <wubo40@huawei.com>
> log:modify iSCSI shared memory permissions for logs 

- usr/iscsid.c
If iscsid is run in --foreground mode and signal handler in iscsid.c catches SIGPIPE (e.g. stderr is unavailable due to stopped systemd-journald service), log_debug() will be executed resulting in SIGPIPE loop rendering the daemon inoperable.
> Fix SIGPIPE loop in signal handler

- usr/initiator.c
1. Due to configuration issues, the logins from iSCSI initiator were getting rejected by the target
2. The initiator was retrying the login again and again
3. Each time the initiator tries to log in, the host number gets incremented by 1
4. At one point of time, the host number reached 65535
5. During the login process, once the TCP connection is established, the initiator tries to set the host parameters for the network interface if its not the default interface
6. While setting these host parameters, it will try to do a lookup of the host based upon the host number
7. The host number in "iscsi_uevent" structure is uint32_t. This is given as an argument to the scsi_host_lookup() function
8. This scsi_host_lookup() function takes it as unsigned short. So, when it receives the host number …
> Proper disconnect of TCP connection

- etc/systemd/iscsi-init.service
- etc/systemd/iscsi.service
Per Fedora Packaging Guidelines [1], initial configuration of a service
should happen in a one-off init service in order to ensure idempotency,
and not in the %post directive of the RPM spec.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1493296
[1]: https://docs.fedoraproject.org/en-US/packaging-guidelines/Initial_Service_Setup/
> Add iscsi-init.service

- include/iscsi_if.h
- iscsiuio/src/uip/ipv6.c
- iscsiuio/src/unix/nic_utils.c
These commits make the gcc-10 compiler happier, eliminating all but a few iscsiuio packed-vs-aligned warnings.
> Fix zero length array usage, and some iscsiuio compiler issues

- utils/fwparam_ibft/fwparam_ibft.c
iscsi-review/utils/fwparam_ibft/fwparam_ibft.c: line 466
Before return -1, the fd was opend and not closed which would lead
to leak fd. Fix that.
Signed-off-by: lixiaokeng<lixiaokeng@huawei.com>
Reported-by: Zhiqiang Liu <liuzhiqiang26@huawei.com>
> iscsi: fix fd leak

- utils/fwparam_ibft/fwparam_sysfs.c
Fix the potential risk of rc value being washed out by jumping out of the loop
Signed-off-by: liubo <liubo254@huawei.com>
Reported-by: Zhiqiang Liu <liuzhiqiang26@huawei.com>
> iscsi: Add break to while loop

- libopeniscsiusr/Makefile
when I make install for libopeniscsiusr.  the libopeniscsiusr_node.h does not be installed. so add libopeniscsiusr_node.h to the Makefile.
#cd open-iscsi/libopeniscsiusr
#make 
#make install
#ll -l /usr/include/libopeniscsiusr* 
-rwxr-xr-x. 1 root root 2.3K Jun 15 16:43 /usr/include/libopeniscsiusr_common.h
-rwxr-xr-x. 1 root root  16K Jun 15 16:43 /usr/include/libopeniscsiusr.h
-rwxr-xr-x. 1 root root 6.8K Jun 15 16:43 /usr/include/libopeniscsiusr_iface.h
-rwxr-xr-x. 1 root root  13K Jun 15 16:43 /usr/include/libopeniscsiusr_session.h
Signed-off-by: Wu Bo <wubo.kernel@gmail.com>
> iscsi/libopeniscsiusr:Fix libopeniscsiusr_node.h file is not installed

- doc/iscsiadm.8
- usr/iscsiadm.c
Add a "no wait" flag to iscsiadm, for use when it is logging into
all targets of a certain "type", i.e. using the "--loginaall=" option,
which iscsiadm will pass to the login_by_startup() routine. The
wait/no-wait code was already present there, so just hook into
it.
NOTE: this means that "iscsiadm -m node ... -L=all -W" will return
success if it is able to send a login request for each node, whether
or not the logins succeed.
The man page and usage info was also updated to document this new flag.
> Add ability to attempt target logins asynchronously

- usr/initiator.c
Description
-------------
If the initiator is rebooting then after the reboot, it will try to resync (recreate) the existing the connections by reading the sysfs. While initiator is doing this, i.e when the initiator tries to connect to the target but if the target service is not yet started, then the initiator connection will fail. The session id is also not yet assigned and it will be at its initial value 0xFFFFFFFF which is invalid. The session id is assigned a valid value only after a successful connection. Since the connection is failed, the initiator code will queue the connection for re-open. The connection state is still at ISCSI_CONN_STATE_XPT_WAIT as its very first login attemp after the reboot. 
Due to my Pull #206 request the code will invoke the stop connection to decrement …
> Check Invalid Session id for stop connection

- libopeniscsiusr/idbm.c
This compares value member of int_list_tbl struct which is of unsigned
int type.
struct int_list_tbl {
const char *name;
unsigned int value;
};
Clang compiler reports this comparison when
-Wtautological-constant-out-of-range-compare is enabled
| idbm.c:1042:2: error: result of comparison of constant 18446744073709551615 with expression of type 'unsigned int' is always true [-Werror,-Wtautological-constant-out-of-range-compare]
|         _rec_int_list(SESSION_CHAP_ALGS, recs, node, session.auth.chap_algs,
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| idbm.c:263:23: note: expanded from macro '_rec_int_list'
|                 if (_org->_name[_i] != ~0UL) { \
|                     ~~~~~~~~~~~~~~~ ^  ~~~~
Since max value for int can be less than unsinged long …
> libopeniscsiusr: Compare with max int instead of max long

- usr/sysfs.c
strlen(sysfs_value) return 0 do not mean sysfs_value
is NULL and this memory should be freed
> Fix memory leak in sysfs_get_str

- usr/iscsid.c
- usr/log.c
Some users monitor syslog by logging level. Inappropriate logging level breaks their monitoring because of false alert.
> iscsid: fix logging level when starting and shutting down daemon

- usr/iscsi_sysfs.c
- usr/iscsi_sysfs.h
- usr/iscsid_req.c
Description
===========
This patch has the following two changes
------------------------------------------
Change 1: Specify the poll timeout value to 1 minute as third parameter
to the function iscsid_exec_req() when called from sync_session()
Reason: Currently the poll timeout value sent sent to iscsid_response()
from iscsid_exec_req() is "info->iscsid_req_tmo" which is -1 as set in
"iscsi_sysfs_for_each_session()". When iscsid_response() receives this
-1, it sets the timeout value to ISCSID_REQ_TIMEOUT (1000 ms) and also
sets a local variable "poll_wait" to 1. There is a while loop below this
which checks the value of "poll_wait". If "poll_wait" is set to 1, then
it calls "continue". For sessions which are giving continuous connection
errors (like target service stopped OR target node …
> iscsid: Poll timeout value to 1 minute for iscsid

- Makefile
iscsi-init.service is not included in the `SYSTEMDFILES` Makefile variable, causing it to be skipped when the `install_systemd` rule is executed. This causes the `iscsi` systemd service to fail on a fresh install, as it requires the `iscsi-init` service.
This PR adds `etc/systemd/iscsi-init.service` to the list of files in `SYSTEMDFILES` to correct this issue.
> Add etc/systemd/iscsi-init.service to SYSTEMDFILES Makefile variable

- libopeniscsiusr/idbm.c
- libopeniscsiusr/iface.c
- usr/idbm.c
- usr/iface.c
- usr/iscsiadm.c
- usr/iscsid.c
- Change mkdir() permissions from 0660 to 0770 so that there
are not SELinux dac_override violations.
- Adjust the umask to preserve execute bit permission on directories
created in iscsid and iscsiadm.
The reasons for this PR can be found in https://bugzilla.redhat.com/show_bug.cgi?id=1911161 but the short version is that there will be an SELinux AVC denial without the execute bit being set on directories.
> Change mkdir permissions to 0770, adjust umask

- usr/Makefile
When building with `NO_SYSTEMD=1` set the `-DNO_SYSTEMD` `CFLAG`, otherwise the `iscsid` build tries to include the systemd header and aborts:
```
iscsid.c:38:10: fatal error: systemd/sd-daemon.h: No such file or directory
```
> iscsid: Add NO_SYSTEMD to CFLAGS

- usr/iscsistart.c
Earlier commit 9258c8eae046 changed the return value fron
iscsid_response() from ISCSI_ERR_ISCSID_NOTCONN to
ISCSI_ERR_SESSION_NOT_CONNECTED in the case where no iscsi response is
received when expected.
This effected the login code in iscsistart when the target is not
completely ready at iscsi login time. This commit updates iscsistart
to expect the new error code, but fixing this uncovered another issue,
causing iscsistart logins to continue to fail if the target returned its
login response too slowly.
This commit ups the timeout time for iscsistart logins from 1 second per
try to 10 seconds per try. This is perhaps excessive, and a shorter
delay would be more appropriate, but the retry/nanosleep logic in
iscsistart meant to retry the login in such cases seems problematic in
this case, …
> Fix iscsistart login issue when target is delayed.

- iscsiuio/configure.ac
Debian Bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982307
Patch from @helmutg.
> Avoid hardcoding pkg-config to fix cross build

- etc/systemd/iscsi.service
- etc/systemd/iscsid.service
Add the "-W" (no wait) flag to the iscsiadm login command in
iscsi.service, so that the service succeeds even if one or more
of the targets being logged on to is not available at startup
time.
Also, clean up the iscsi.service and iscsid.service files.
> Enable iscsi.service asynchronous logins, cleanup services

- libopeniscsiusr/libopeniscsiusr/libopeniscsiusr.h
- libopeniscsiusr/session.c
- libopeniscsiusr/sysfs.c
iscsiadm issues with libopeniscsiusr code returning an error when reading all session attributes from sysfs while sessions are being created and destroyed.  Reported from an OpenStack configuration.
I'm going to wait a bit and see if I can get some better testing confirmation from the original reporter, but I expect this will work.  Will merge once fix is confirmed.
> Iscsi sessions get

- usr/login.c
Log the correct error message in /var/log/messages when the debug status is set when there is an authentication error. The change is made in check_security_stage_status() function. This issue was identified when one of the customer was trying to login to the iscsi target after configuring the mutual CHAP authentication. They set the same password for both side authentication. This is not allowed as per the code as it was returning AUTH_DBG_STATUS_PASSWD_IDENTICAL. The error logged in /var/log/messages was not obvious. This change will help to understand the correct error message so that required action can be taken.
> Log error message when auth debug status is set

- usr/iscsistart.c
In login_session() function, we need to check for error ISCSI_ERR_ISCSID_NOTCONN also. When the login command is sent to the iscsid using iscsid_exec_req(), it will try to connect to iscsid using the function ipc_connect(). If there is an issue in iscsid or if we are not able to create the socket due to some reason, then the error ISCSI_ERR_ISCSID_NOTCONN is returned. We need to retry the login command by checking the error ISCSI_ERR_ISCSID_NOTCONN.
> Check ISCSI_ERR_ISCSID_NOTCONN in iscsistart login

- usr/idbm.c
When "iscsiadm -m discovery -t fw" is ran, nodes are
created/updated in the node DB for each firmware target
found, but the 'startup' mode values are left as 'manual',
when in fact firmware nodes are treated as if this
value is 'onboot'. So to keep the node DB in sync with
behavior, set these to 'onboot' by default. This
should *not* effect any other functionality.
> Set default 'startup' to 'onboot' for FW nodes

- usr/iscsistart.c
Fixes regression caused by "open-iscsi: Clean user_param list when
process exit"  Which is a shame, as not freeing a memory at process exit
doesn't really hurt anything.
Same change as "Fix iscsiadm segfault when exiting" applied to iscsiadm.
Fixes: b532ad67d495d42026165a26515c645995d23f18
Signed-off-by: Chris Leech <cleech@redhat.com>
> iscsistart: fix null pointer deref before exit

- utils/iscsi_offload
The iscsi_offload command needs to recognize the "qede" driver.
> Support the "qede" CNA-card driver.

- usr/iscsid.c
When iscsid makes syscalls that lead to memory allocations the kernel
might use GFP_KERNEL. This can lead to pages being written to iscsi
disks managed by iscsid. If we are doing a syscall to try and reconnect
the session the disk is accessed through then we could deadlock.
When in the iscsi layer we can select our GFP flags but when making
syscalls to the network layer we have to set PR_SET_IO_FLUSHER so we
use the correct GFP flags.
Signed-off-by: Mike Christie <michael.christie@oracle.com>
> iscsid: set PR_SET_IO_FLUSHER

- usr/iscsid_req.c
Description:
------------
Due to any issue on target side or any other underlying network issue, the initiator will get "connection refused" error when it tries to connect to the iscsi target. Once it gets the connection refused error, the error handler will try to re-connect to the target after 3 seconds and this will be repeated till the timeout of 120 seconds for the initial login. After this, the connection will be terminated and shutdown.
After this, when the image installation started to upgrade the iscsi-initiator-utils, first systemd tried to Reload the daemon and started tryign to login iscsi devicces, which triggered the iscsi connection to the target which was down (for which we had the initial login failed as mentioned above). This trigger of connection was from the iscsiadm …
> Handle recv() returning 0 in iscsid_response()

- doc/iscsiadm.8
- etc/iface.example
- include/iscsi_if.h
- libopeniscsiusr/idbm.c
- libopeniscsiusr/iface.c
- usr/iface.c
- usr/iface.h
- utils/iscsi_offload
These commits fix up some of the ipv6 vs ipv4 interface logic, code that has largely been unused so far. Testing done on several types of offload cards using IPv6 and IPv4.
The externally-visable difference will be that interface files created by iscsiadm will generally be named, now, ending in "ipv4.N" or "ipv6.N", where "N" is the interface number (generally 0).
> Handle ipv6 better

- libopeniscsiusr/idbm.c
Commit 76350316de38 ("Handle IPv6 interfaces correctly.") added
a string copy that creates this gcc-11 error message:
> gcc-11 -O2 -g -Wall -Werror -Wextra -fvisibility=hidden -fPIC -I/usr/include/kmod    -c -o idbm.o idbm.c
> idbm.c: In function ‘_idbm_node_rec_link’:
> idbm.c:999:17: error: ‘strncpy’ specified bound 65 equals destination size [-Werror=stringop-truncation]
>   999 |                 strncpy((*node).iface.name, iface_name, ISCSI_MAX_IFACE_LEN);
>       |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
So copy one less character, maximum.
> Fix compiler error introduced with recent IPv6 commit.

- etc/systemd/iscsi-init.service
Since iscsid.service depends on it but disables
default dependencies, iscsi-init.service must
also disable default dependencies, or a dependency
loop can be created.
> Remove dependences from iscsi-init.service

- Makefile
- etc/systemd/iscsi-init.service
- etc/systemd/iscsi.service
- etc/systemd/iscsid.service
- etc/systemd/iscsiuio.service
Use a variable for the sbin directory where executables
go in our systemd unit files, so that the files can
be configured, during installation, to have the
correct path, instead of just hard-coding these paths.
Now "make sbindir=/SOME/PATH ..." works correctly for
different paths.
> Use "sbindir" for path in systemd service files

- etc/systemd/iscsi-init.service
A recent commit, 432bbf979ee6 ("Remove dependences
from iscsi-init.service") removed DefaultDependencies from
iscsi-init.service, but that now means it can run so
early that the root disc is not yet writable, rendering
it useless, since it can't create the initiatorname.iscsi
file. This change tells it to wait until root is writable
to run.
> Fix iscsi-init so that it runs when root writable

- usr/iscsiadm.c
log_init() should be called before log_error() been called
> iscsiadm: Call log_init() first to fix a segmentation fault

- Makefile
- doc/iscsi-gen-initiatorname.8
- utils/iscsi-gen-initiatorname
Fix the "iscsi-gen-initiatorname" script. This started because it ignored the error when the initiator name file was read-only, but I decided to clean up as much of the command as I could.
I also added the ability to set the IQN prefix, instead of using the "SUSE" default, so that other distros could use this script, if they wish.
> Fix iscsi-gen-initiatorname

- libopeniscsiusr/sysfs.c
The kernel change
"e746f3451ec7 scsi: iscsi: Fix iface sysfs attr detection"
fixed an apparently very-long-standing issue blocking iface attribute
visibility in sysfs.
With that fixed, and networking configuration for the iface now being
readable from sysfs, iscsiadm is showing errors when be2iscsi (and
probably qla4xxx from looking at the code) expose VLAN attributes but
don't have a VLAN configured.  Both drivers then return EINVAL on a read
to vlan_id or vlan_priority.
iSCSI ERROR: Error when reading '/sys/class/iscsi_iface/ipv4-iface-17-0/vlan_id': 22 # sysfs.c:iscsi_sysfs_prop_get_ll():282
iSCSI ERROR: Error when reading '/sys/class/iscsi_iface/ipv4-iface-17-0/vlan_priority': 22 # sysfs.c:iscsi_sysfs_prop_get_ll():282
This change makes the libopeniscsiusr code ignore a read return of …
> libopeniscsiusr: extend sysfs ignore_error to include EINVAL

- include/iscsi_err.h
- usr/iscsid_req.c
- usr/iscsistart.c
This fixes a bug where iscsistart would exit before we've waited for the login to complete or fail. It also cleans up some related code.
This is a followup to:
https://github.com/open-iscsi/open-iscsi/pull/275
> iscsistart fix and timeout cleanup

- usr/iscsi_err.c
Commit 67eb8b2 added error code ISCSI_ERR_REQ_TIMEOUT.
While did not update array iscsi_error_list which referenced
in iscsi_err_to_str(). Which would access a invalid memory with
when variable of iscsi_err_to_str() is ISCSI_ERR_REQ_TIMEOUT.
> iscsi_err: Add iscsid request timed out error messages

- usr/auth.c
- usr/discovery.c
- usr/iscsi_sysfs.c
- usr/login.c
Gcc-12 caught a few errors in the code where we were checking
for an array being empty incorrectly, so this commit fixes those.
> Fix issues discovered by gcc12

- Makefile
systemd files should be installed to path "/usr/lib/systemd/system", 
while previous implement installs these files to "/usr/lib/systemd/system/system".
Following error would reported by systemd when start iscsid.service:
```
root@fedora ~:# systemctl status iscsid.service 
Unit iscsid.service could not be found.
```
> Fix wrong install_systemd destination path

- usr/initiator.c
- usr/iscsid.c
This PR fix one possible issue which described in https://github.com/open-iscsi/open-iscsi/pull/288
If session id has already been synced just return ISCSI_ERR_SESS_EXISTS.
A same session id would make two MGMT_IPC_SESSION_SYNC requests in
following scenario:
iscsid.socket is enabled, and iscsid did not handle previous
MGMT_IPC_SESSION_SYNC due to abnormal exit. This MGMT_IPC_SESSION_SYNC
request would left unhandled, when iscsid restart again, newly started
iscsid can get this MGMT_IPC_SESSION_SYNC request.
While the newly started iscsid would make a MGMT_IPC_SESSION_SYNC
request for same session id too.
So here should check if the session id has already been synced.
> Fix multiple sync of a same session id

- utils/iscsi-gen-initiatorname
This script can be called early in the boot process,
when /tmp is not writable (but /etc/iscsi is), so
change the usage of HEREIS to simple variables.
Otherwise, no change in functionality.
> Remove HEREIS usage from iscsi-gen-initiatorname

- usr/initiator.c
- usr/initiator.h
- usr/mgmt_ipc.c
There are many logs like following which are not helpful to
locate problem when there are multiple sessions:
"unsupported opcode 0xxxx"
We can not know which connection or session the log belongs to,
so this PR find these logs and add session id, connection id
for them.
This would be helpful to locate problems according to logs.
> Make session and connect log helpful to locate problem

- etc/systemd/iscsi-init.service
The commit e6e53d6e60bf ("Fix iscsi-init so that it runs when
root writable") added "After=root.mount" to iscsi-init.service,
but that was an error, since that means waiting for "/root".
Remove that line and add the proper configuration so that
the iscsi-init service does not try to write to
/etc/iscsi/initiatorname.iscsi unless /etc/iscsi is
writable.
Fixes: e6e53d6e60bf
> Fix iscsi-init.service start time

- usr/initiator.c
If iscsi_send_logout() is called from iscsi_stop() or
session_login_task() and return 0, the next logout flow such as
session_conn_shutdown() depends on target's logout response and
logout timeout.
While if iscsi_send_logout() failed to trigger a logout timeout task,
and target's logout response absent, the logout flow would hang.
So we should return error if iscsi_send_logout() failed to trigger
a logout timeout task.
And add comment about handle logic if iscsi_send_logout() failed from
iscsi_recv_async_msg() by hand.
> return ENOMEM if failed to get ev_context in iscsi_send_logout()

- Makefile
- README
- libopeniscsiusr/Makefile
Cleaning up the Makefiles, in preperation for adding the
ability to move files out of /etc/iscsi more easily. Also,
clean up the README file by updating it with updated
help messages, alignment, and those pesky spaces at the ends of lines.
> General Makefile/README cleanup

- doc/iscsiadm.8
- usr/iscsiadm.c
Updated from previous pull request #318 which will be replaced by this one.
Changes from that request:
- unrelated man page cleanup done separately, mostly (one small cleanup snuck in)
- removed ability to override interface values, instead now failing with an error message
- changed iscsistart-specific comment in new code to be firmware-login-specific
- Also removed validation of interface name changes, since they were node-specific and no longer needed, since we disallow interface value changes
Has been tested in Virtual Machine using iscsi multipath root disc.
> Firmware login: add nv pairs and default values v2

- Makefile
- README
- doc/.gitignore
- doc/Makefile
- doc/iscsi-gen-initiatorname.8.template
- doc/iscsiadm.8.template
- doc/iscsid.8.template
- etc/Makefile
- include/iscsi_net_util.h
- iscsiuio/.gitignore
- libopeniscsiusr/Makefile
- libopeniscsiusr/idbm.h
- libopeniscsiusr/node.h
- usr/Makefile
- usr/idbm.c
- usr/idbm.h
- usr/iface.c
- usr/iface.h
- usr/initiator.h
- usr/iscsid.c
- usr/iscsid_req.c
- utils/Makefile
- utils/fwparam_ibft/Makefile
- utils/iscsi-gen-initiatorname.sh.template
This large commit adds "DBROOT=/some/dir" and "HOMEDIR=/some/other/dir" options to the Makefiles, so that files can be moved out of /etc/iscsi if desired. DBROOT is for the database files, which some distributions have already moved to /var/lib/iscsi -- so this might make that easier. HOMEDIR is where iscsid.conf and initiatorname.iscsi live. Both still default to /etc/iscsi, for now, though my hope is that the database files will moved to /var/lib/iscsi, by default, soon.
> Make etc iscsi configurable

- usr/fwparam_ibft/fwparam_ppc.c
- usr/fwparam_ibft/fwparam_sysfs.c
Moving these files, as done recently, means they now can
be compiled with different (more strict) options, so mark
unused params as such. There is no functional change.
> Fix gcc issues with unused params in fwparam

- Makefile
- etc/Makefile
- etc/systemd/ibft-rule-generator
- libopeniscsiusr/Makefile
- usr/Makefile
- utils/Makefile
This pull request contains a few build-bug fixes as well as some cleanup needed to fix those. Also, a new systemd generator is added that generates udev rules for iBFT connections. Bugs fixed: DESTDIR was doubled for some components, libopeniscsiusr man pages are installed now, and a debug echo statement accidentally left in a Makefile was removed.
> Latest build cleanups and butg fixes

- doc/iscsi-gen-initiatorname.8.template
- utils/iscsi-gen-initiatorname.sh.template
This pull request updates iscsi-gen-initiatorname so that it gets the iSCSI InitiatorName value from the kernel command line, if present, when setting the initiator name in initiatorname.iscsi.
The man page is also updated. The script was refactored to make the logic less convoluted, and to explicitly check for the caller being root.
> Use kernel initiatorname if present

- iscsiuio/configure.ac
- iscsiuio/src/unix/Makefile.am
- libopeniscsiusr/Makefile
- usr/Makefile
- usr/fwparam_ibft/Makefile
- utils/Makefile
- utils/sysdeps/Makefile
Hi,
These are a few patches we've been maintaining downstream in Gentoo which should help general distribution folks out.
> Build system tweaks from downstream

- usr/fwparam_ibft/Makefile
- usr/fwparam_ibft/README
This build has lex and bison source files, but
they are not normally used to regenerate C files,
since that has been done ahead of time, statically,
to handle the case when users building the software
may not have these tools. But some build systems
think the generated C files need to be regenerated
because the timestamp on the source and generated
files is so close, just because of the order the
files were populated in this directory. So we tell
the Makefile to only generate C files if those
files are missing. This should have no effect,
since these files should never need to be
regenerated unless we change lex or bison logic.
> Make fwparam_ibft build more reliable.

- etc/systemd/ibft-rule-generator
Commit fe2c59e06a42 ("Create an systemd iBFT rule generator")
created ibft-rule-generator, but it contains a syntax error,
causing this error message when its run:
> /usr/lib/systemd/system-generators/ibft-rule-generator: line 21: IBFT_RULE_DIR: command not found
This fixes that error.
> Fix ibft-rule-generator shell error

- iscsiuio/src/unix/Makefile.am
iscsiuio: fix LDADD
- We don't want to use _LIBS here, we're building a library, not an executable.
- We want LDADD for the whole lot (not a mix of LDFLAGS/LIBS/LDADD),
but put the objects/libraries (.a files) first so that -l* works correctly.
Closes: https://github.com/open-iscsi/open-iscsi/issues/337
Fixes: 9fbd6009cd917f1152a367fa7e5ae3993133c1e4
Signed-off-by: Sam James <sam@gentoo.org>
> iscsiuio: fix LDADD

- usr/initiator.c
This fixes a bug where when we send logout pdu we are incorrectly
handling it as an error. This was added in
https://github.com/open-iscsi/open-iscsi/pull/317
I think there might have been a mistake for which version of that patch
got merged because there are some unhandled review comments in the merged
code.
The patch also fixes some review comments that were given in that review
but were not handled when it was merged:
1. No space before "Dropping session"
2. Don't split error messages.
> iscsid: fix logout pdu send failure detection handling

- Makefile
- doc/Makefile
- etc/Makefile
- libopeniscsiusr/Makefile
- usr/Makefile
- utils/Makefile
- utils/sysdeps/Makefile
This cleans up a little more than "make clean",
in particular removing files generated from templates,
and automake-generated files in iscsiuio.
Also, a ".PHONY:" target was added where needed
so that each Makefile has a complete list of
phony targets.
> Add a 'distclean' Makefile top-level target

- doc/Makefile
- doc/iscsistart.8.template
- usr/idbm.c
- usr/iscsiadm.c
- usr/iscsistart.c
Specifying name-value pairs as arguments to iscsistart or
iscsiadm can become unwieldy very quickly, and is less flexible
than using a config file. If a user desires to update settings,
modifying a config file and rebuilding initramfs can be simpler
than modifying arguments directly in initramfs code or scripts.
Node records created from boot context are populated with
defaults, then any settings specified in a config file are
applied (if config is present).
FW and user-specified params are still applicable. User-specified
name-value arguments are applied after config settings, so they
can serve as a safeguard against config file changes if
desired.
Added -c|--config options for iscsistart to specify the config
Updated iscsistart man page
Signed-off-by: Eric Mackay …
> Use config for iscsistart and iscsiadm fw login

- usr/iscsiadm.c
Add ability to specify name-value parameters when creating a new iface
like following:
root# iscsiadm -m iface -I test -o new -n iface.initiatorname -v iqn.2016-04.com.open-iscsi:17a3c9bc2d
test updated.
New interface test added
root# iscsiadm -m iface -I test | grep initiatorname
iface.initiatorname = iqn.2016-04.com.open-iscsi:17a3c9bc2d
> Add ability to specify name-value parameters when creating a new iface

- README
The README's error handling and timeout section is out dated or not
correct. This patch updates it.
> Update README's error handler/timeout section

- doc/Makefile
- etc/Makefile
- libopeniscsiusr/Makefile
- utils/Makefile
Just use PATH to find sed. Not all distributions have moved to a /usr-merged
layout yet.
For Debian I had to patch this, as we still need to build on layouts where sed is (only) in /bin/sed. I think this should work just fine on Fedora, SUSE, etc.
> make: avoid hard-coding path to sed

- doc/.gitignore
- usr/fwparam_ibft/Makefile
Two changes: (1) add generated man pages to git ignore list, and (2) remove dependency on libopeniscsiusr from usr/fwparam_ibft.
> Cleanup fwparam makefile

- iscsiuio/src/unix/options.h
pthread_t is opaque, therefore avoid compiler errors on musl when
compiling since pthread_t is not a plain old data type, like glibc
Signed-off-by: Khem Raj <raj.khem@gmail.com>
> iscsiuio: Use pthread_t for INVALID_THREAD

- libopeniscsiusr/session.c
Fix build errors when not using glibc.
> Use realloc instead of reallocarray

- libopeniscsiusr/session.c
Just adding more comment, and removing the check
to see if a pointer to a structure is zero.
> libopeniscsiusr: cleanup recent reallocarray->realloc change

- meson_options.txt
Use env. variable KBUILD_BUILD_TIMESTAMP to acheive reproducable builds.
> meson: remove unused 'source_date_epoch' option

- iscsiuio/src/unix/main.c
- usr/iscsi_util.c
- usr/iscsid.c
For both the iscsid and iscsiuio daemons, they try to modify nice value and OOM adjustment value, so they have priority and will not be killed by the OOM-killer.
But the code incorrectly set the value to "-17" for modern linux systems, when the maximum is actually "-1000". While making the changes, use "/proc/self/..." instead of "/proc/<PID>/...", so we don't have to use getpid() nor print out the pathname. Now we either write "-16" to the old interface, "-1000" to the new interface, or we print a warning.
Several "log_debug()" calls that should have been warnings are changed to "log_warning()" calls in iscsid.
> iscsid/iscsiuio: fix OOM adjustment

- usr/iscsi_sysfs.c
- usr/iscsi_util.c
- usr/iscsi_util.h
- usr/iscsid.c
commit 72949ef (iscsid: set PR_SET_IO_FLUSHER) set the iscsid's PR_SET_IO_FLUSHER flag to avoid deadlock. While we do not need to set this flag when scanning host.
If this flag is set for scanning thread, we may lost devices reported by target because of memory allocation failure.
Reference: #381 
> iscsid: clear scanning thread's PR_SET_IO_FLUSHER flag

- etc/iscsid.conf
Remove the comment in the config file saying where it might be located, since it was incorrect, and
users already know where it's located if they are
reading the comment.
> iscsid.conf: remove incorrect comment about location

- meson_options.txt
Change DB home (for nodes, send_targets, etc) from /etc/iscsi to /var/lib/iscsi. This can still be
overridden with the "-dbroot" option with meson.
> Build: change meson default for DB home

- etc/iscsid.conf
- usr/event_poll.c
- usr/iscsi_ipc.h
- usr/iscsid.c
- usr/iscsistart.c
- usr/mgmt_ipc.c
- usr/mgmt_ipc.h
Modern security practices include checking the originating UID of an IPC. But not the username, as there are many valid scenarios where a user database may not exist or the root account may not be explicitly named "root".
The mode to check UID and username is still functional, but is now on the path to deprecation. Related function names and enums now include the term "legacy" to indicate this deprecated status.
The 'iscsid.ipc_auth_uid' setting in iscsid.config now defaults to 'Yes', rather than introducing a new key. Users sometimes keep old config files when upgrading packages, and this ensures behavior remains the same if this setting was explicitly defined in an old config.
Signed-off-by: Eric Mackay <eric.mackay@oracle.com>
Reviewed-by: Mike Christie <michael.christie@oracle.com>
> Make UID the default auth type for IPCs

- README
- libopeniscsiusr/COPYING
- libopeniscsiusr/context.c
- libopeniscsiusr/context.h
- libopeniscsiusr/default.c
- libopeniscsiusr/default.h
- libopeniscsiusr/docs/libopeniscsiusr.h.3
- libopeniscsiusr/idbm.c
- libopeniscsiusr/idbm.h
- libopeniscsiusr/idbm_fields.h
- libopeniscsiusr/iface.c
- libopeniscsiusr/iface.h
- libopeniscsiusr/libopeniscsiusr/libopeniscsiusr.h
- libopeniscsiusr/libopeniscsiusr/libopeniscsiusr_common.h
- libopeniscsiusr/libopeniscsiusr/libopeniscsiusr_iface.h
- libopeniscsiusr/libopeniscsiusr/libopeniscsiusr_node.h
- libopeniscsiusr/libopeniscsiusr/libopeniscsiusr_session.h
- libopeniscsiusr/misc.c
- libopeniscsiusr/misc.h
- libopeniscsiusr/node.c
- libopeniscsiusr/node.h
- libopeniscsiusr/rfc.h
- libopeniscsiusr/session.c
- libopeniscsiusr/sysfs.c
- libopeniscsiusr/sysfs.h
- libopeniscsiusr/tests/test_context.c
- libopeniscsiusr/tests/test_iface.c
- libopeniscsiusr/tests/test_node.c
- libopeniscsiusr/tests/test_session.c
The library was licensed GLPv3, but LGPLv3 is more appropriate for a library used widely by others.
The change is done with permission of the library
author, after some discussion.
This will effectively upgrade the license, in
practice, for open-iscsi, to GPLv3, without
having to actually change the higher-level license.
> Fix libopeniscsiusr licensing

- doc/Makefile
- doc/iscsi-iname.8.template
- doc/meson.build
- meson.build
- meson_options.txt
- utils/Makefile
- utils/iscsi-iname.c
Packagers might want to change the default IQN prefix to use their own domain name information.  Provide a build time option for that.
> iscsi-iname: make default IQN prefix configurable

- README
- doc/Makefile
- doc/iscsi-iname.8.template
- doc/iscsiadm.8.template
- doc/meson.build
- meson.build
- meson_options.txt
- usr/Makefile
- usr/discovery.c
- usr/discovery.h
- usr/discoveryd.c
- usr/iscsiadm.c
- utils/Makefile
- utils/iscsi-iname.c
In some cases open-isns may not be needed or may not be available. Make building without it optional, using meson. The depricated Makefile build is not effected.
> Build: make open-isns usage optional.

- etc/systemd/iscsiuio.service.template
The correct syntax is "BindsTo", but we do not
actually want to use this, because it would imply
that iscsid.service needs to be started _before_
iscsiuio.service, but that is backwards.
Found by: Martin Wilck @ SUSE
> Remove incorrect "BindTo" line in iscsiuio.service

- iscsiuio/README
- iscsiuio/RELEASE.TXT
- iscsiuio/configure.ac
- iscsiuio/src/unix/libs/qedi.c
- iscsiuio/src/unix/nic_utils.c
Hi,
Please merge the iscsiuio fixes for the issues due to iscsiuio coredump upon service restart in iSCSI MPIO boot from SAN config causing intermittent OS boot failures.
Thanks,
Nilesh
> iscsiuio 0.7.8.7

- Changelog
- Makefile
- meson.build
> Preparing for version 2.1.9

- etc/iscsid.conf
Trivial fixup.  I ran into a test script that failed becuase iscsid.conf wasn't ASCII.  I like UTF-8, but none of this code handles it. And while unicode bytes in a comment shouldn't be the end of the world, it's just a lot clearer to remove the single offending symbol.
> remove unicode symbol from iscsid.conf

- usr/discoveryd.c
Similar to #413, these were seen compiling with -O3
> discoveryd: fix additional format overflow warnings

- usr/idbm.c
Fix the following musl build failure raised since version 2.1.9 and https://github.com/open-iscsi/open-iscsi/commit/7b571d76d6937a78c141630fc38c3c57c532466c:
```
../usr/idbm.c: In function 'idbm_rec_write_old':
../usr/idbm.c:2230:27: error: 'GLOB_ONLYDIR' undeclared (first use in this function)
2230 |         rc = glob(portal, GLOB_ONLYDIR, NULL, &globbuf);
|                           ^~~~~~~~~~~~
```
Fixes:
- http://autobuild.buildroot.org/results/14fc1c139f055b5b1eaa6e04e327863c06176a7b
> usr/idbm.c: fix musl build

- iscsiuio/src/unix/libs/cnic.c
- iscsiuio/src/unix/main.c
- iscsiuio/src/unix/nic.c
- iscsiuio/src/unix/nic.h
- iscsiuio/src/unix/nic_nl.c
- iscsiuio/src/unix/ping.c
This commit adds ability for iscsiuio to count
threads started, and to wait for them at shutdown, up to 10 seconds maximum. It also adds a few
messages during that shutdown time if threads are
slow to shut down.
Testing showed that 100 iterations of stop/start
of the iscsiuio service completed without error
with these changes.
> iscsiuio: manage threads better at shutdown

- iscsiuio/README
- iscsiuio/RELEASE.TXT
- iscsiuio/configure.ac
- iscsiuio/meson.build
- iscsiuio/src/unix/iscsid_ipc.c
- iscsiuio/src/unix/logger.h
Fixes an issue where iscsiuio would not compile because of the way the logging macros worked. Also, updated iscsiuio version after fixing the logging issue.
> iscsiuio: update version to 0.7.8.8

- iscsiuio/src/uip/uip_arp.c
- iscsiuio/src/unix/iscsid_ipc.c
- iscsiuio/src/unix/libs/cnic.c
- iscsiuio/src/unix/nic.c
- usr/iscsi_net_util.c
The use of inet_aton is in usr/icsi_net_util.c, and the use of inet_ntoa is in iscsiuio/src/...
Use the modern versions, inet_pton and inet_ntop,
which support IPv6, are used instead, but they
require a buffer. See open-iscsi issue #433.
> Stop using deprecated inet_aton and inet_ntoa

- README
The documentation states that the print level can be between 0 and 2, but then lists the levels as 1 to 3.
Is 
Excerpt provided below for context:
```
Print level can be 0 to 2.
1 = Print basic session info like node we are
connected to and whether we are connected.
2 = Print iSCSI params used.
3 = Print SCSI info like LUNs, device state.
```
I've updated the range of values to include 3, and provided a description for print level 0.
> Incorrect documentation for `iscsiadm -m session` print level

- usr/initiator.c
- usr/iscsi_sysfs.c
- usr/iscsi_sysfs.h
- usr/iscsiadm.c
- usr/iscsid.c
If a device goes to offline/transport-offline when we are disconnected the device's size can be set to zero if some other app forces it to get rescanned. Normally in the kernel when a device is set from offline to running again, it will rescan the device. However, because during a relogin the iscsi layer sets the state from offline/transport-offline via iscsi_unblock_session we don't hit that rescan. We actually don't want to hit the kernel's rescan right now, because it can block and that would block all iscsid operations.
This has us perform a rescan operation after a relogin from the scan process.
> iscsid: Rescan devices on relogin

- etc/iscsid.conf
- usr/idbm.h
- usr/initiator.c
- usr/initiator_common.c
This doesn't add any functional changes, but it does add warning messages when authmethod=None and CHAP credentials are configured and used. It also adds a warning when an existing authorization failure occurs, but continues to ignore it (for now).
The documentation on authmethod in iscsid.conf is updated as well.
> Fix authmethod check by printing a warning message when CHAP used and authmethod=None

- usr/iscsi_util.c
- usr/iscsi_util.h
- usr/iscsiadm.c
Commit 4d045cdeaf70 ('iscsi tools: support hostnames in node mode') was supposed to allow hostnames when using iscsiadm in node mode, but it was still comparing the connection address from the node entry with the "-p" hostname passed in, so the test would fail when running something like this:
> # iscsiadm -m discovery -t st -p HOSTNAME
> ...
> # iscsiadm -m node -p HOSTNAME -l
because we were comparing an IP address and a hostname. Instead, use the existing iscsi_addr_match() function created by the commit listed above to compare the HOSTNAME.
> iscsiadm: allow hostnames in node-mode commands

- libopeniscsiusr/idbm.c
- libopeniscsiusr/idbm.h
- usr/idbm.c
- usr/idbm.h
The DB locking was racing, at times, since it did something like:
if (access() != 0)
if (mkdir() != 0)
error
But when multiple processes are running, it is possible for a process to have access() fail, but then mkdir also fail, since another process has created the directory between the check and the attempt at creation. (Note that this error only seemed to occur on first use of iscsiadm, during testing.)
This change essentially makes EEXIST of the directory ok, with some other cleanups of the locking code (in two places).
> Better handle multiple iscsiadm commands

- usr/idbm.c
- usr/idbm.h
- usr/iface.c
During the node discovery process, if there's a memory allocation failure occured in idbm_print(), an empty node DB file will be created silently.
> Make it visible when memory allocation failure

- usr/iscsiadm.c
safe_logout is obtained by applying for strdup in cfg_get_string_param. 
When safe_logout is not a null pointer, there is no place to release it after use, which will cause the risk of memory leaks.
> Fix memory leak in iscsi_check_session_use_count

- usr/iscsi_sysfs.c
The code was using the return value from reading tgt_reset_tmo to decide if it should use the abort_tmo value.
> Fix bug where abort_tmo read failures were ignored.

- libopeniscsiusr/sysfs.c
- usr/sysfs.c
Linux kernel convert session_attr int value "off" to -1 in scsi_transport_iscsi  module. 
But open-iscsi don't convert special value "off" to -1. It will mistake session attibute info display.  
example: If set recovery_tmo "off"(`echo off > /sys/class/iscsi_session/session808/recovery_tmo`), this means  recovery_tmo=-1.  But (`iscsiadm -m session -P 3`) will mistake output "Recovery Timeout: 0".
> Bugfix read specific sysfs value "off" of session attribute

- usr/idbm.c
This makes it so that discovery of firmware targets causes the "startup" values for those discovered nodes to be "onboot".
> Fix fw startup onboot setting

- usr/initiator.c
This fixes a regression added in:
48e683c ('iscsid: Rescan devices on relogin (#444)
For scan=manual we were not sending a response to callers like iscsiadm so they would hang.
See issue:
https://github.com/open-iscsi/open-iscsi/issues/484
> iscsid: Fix hang during login with scan=manual

- include/iscsi_net_util.h
- usr/fwparam_ibft/fw_entry.c
- usr/iscsi_net_util.c
Use IPv4-specific APIs during NIC setup based on iBFT information, regardless of the IP version, which leads to the following error in IPv6-only environments:
Setting up software interface ens300f0np0
iscsistart: Invalid or missing ipaddr in fw entry
Setting up software interface ens300f0np0 failed
To address this, the process now determines the IP version first and calls the appropriate functions to handle NIC setup.
> IPv6 support for iBFT iSCSI boot

- etc/iscsid.conf
- libopeniscsiusr/default.c
- libopeniscsiusr/default.h
- libopeniscsiusr/idbm.c
- libopeniscsiusr/idbm.h
- libopeniscsiusr/idbm_fields.h
- usr/actor.c
- usr/auth.c
- usr/config.h
- usr/discovery.c
- usr/event_poll.c
- usr/idbm.c
- usr/idbm_fields.h
- usr/initiator.c
- usr/initiator.h
- usr/io.c
- usr/iscsi_settings.h
- usr/iscsi_util.c
- usr/iscsiadm.c
- usr/iscsid.c
- usr/log.c
- usr/log.h
- usr/login.c
- usr/session_mgmt.c
When the iscsi targets disappear due to any reason like ports down or the network issues or any other reason, existing sessions will be retried by the iscsi daemon and each retry will have a 3 seconds gap by default. So, the session reopen logs are logged into /var/log/messages for every 3 seconds and due to this the messages file is blown out. To avoid this blow out of messages file, a config parameter is provided in iscsid.conf file in this feature using which a user can tune the interval between the subsequent session reopen log messages By default the value of this config option in iscsid.conf file (node.session.reopen_log_freq) is 1 and is commented out currently.
If user wants to change this value, he can uncomment this option and set the value to a desirable value like 2 or 3 or 4 …
> iscsid: Rate limit session reopen log messages

- usr/auth.c
I'm not sure how this typo has lasted 21 years, but I'm pleased to have found it!
I'm happy to rebase/amend/adjust/give up/etc as desired. :rocket:
Thanks for maintaining Open-iSCSI :heart:
> Fix minor typo ("authenticaton")

- etc/iscsid.conf
- libopeniscsiusr/default.c
- libopeniscsiusr/default.h
- libopeniscsiusr/idbm.c
- libopeniscsiusr/idbm.h
- libopeniscsiusr/idbm_fields.h
- usr/actor.c
- usr/auth.c
- usr/config.h
- usr/discovery.c
- usr/idbm.c
- usr/idbm_fields.h
- usr/initiator.c
- usr/initiator.h
- usr/io.c
- usr/iscsi_settings.h
- usr/iscsi_util.c
- usr/iscsiadm.c
- usr/iscsid.c
- usr/log.c
- usr/log.h
- usr/login.c
- usr/session_mgmt.c
This pull request if for following patches:
1. Modify log function to print session id
2. Change the log_level of log_debug message in actor_delete()
> Modify log function to print session id

- doc/iscsiadm.8.template
As per mane page, we could use "--info" option however that gives an error. Hence slight modifications might be needed to "-r" option.
```
$ man iscsiadm | grep -A1 -B2 '--info'
-r, --sid=sid | sysfsdir
Use  session  ID sid. The session ID of a session can be found from running iscsiadm in session
mode with the --info argument.
$ iscsiadm -m session --info
iscsiadm: unrecognized option '--info'
iscsiadm: session mode: option '-?' is not allowed/supported
```
-----------------
We could fetch the desired details without "--info" or by using "show" or "info" option 
```
SID: 7
root@localhost:~# iscsiadm -m session info
tcp: [7] 10.76.241.0:3260,1 iqn.2025-03.com.example:server1 (non-flash)
root@localhost:~# iscsiadm -m session
tcp: [7] 10.76.241.0:3260,1 iqn.2025-03.com.example:server1 …
```
> doc: fixup iscsiadm man page option for -r

- usr/initiator.c
There seems to be a typo in this warning regarding session priority. 
"throughout" should be throughput.
Thanks!
> Fix a typo in initiator.c

- Makefile
| cd iscsiuio; autoreconf --install
| make: *** No rule to make target 'iscsiuio/Makefile.in', needed by 'iscsiuio/Makefile'.  Stop. | make: *** Waiting for unfinished jobs....
| libtoolize: putting auxiliary files in '.'
iscsiuio/Makefile.in will automatically generated when generate iscsiuio/configure by "cd iscsiuio; autoreconf --install", no need to explicitly specify
> Makefile: fix "No rule to make target 'iscsiuio/Makefile.in" issue

- usr/fwparam_ibft/fwparam_ppc.c
| fwparam_ppc.c:349:45: error: 'calloc' sizes specified with 'sizeof' in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
|   349 |                         dev = calloc(sizeof(struct ofw_dev), 1);
|       |                                             ^~~~~~
| fwparam_ppc.c:349:45: note: earlier argument should specify number of elements, later size of each element
> fwparam_ppc.c: Fix the calloc-transposed-args issue
